"""initial current rental market schema

Revision ID: 2ae09c5a716a
Revises: 
Create Date: 2026-06-18 00:34:24.353573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae09c5a716a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'manager', name='admin_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'BANNED', name='account_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_admins_telegram_id'))
    )
    op.create_index('ix_admins_account_status', 'admins', ['account_status'], unique=False)
    op.create_index('ix_admins_is_active', 'admins', ['is_active'], unique=False)
    op.create_index('ix_admins_role', 'admins', ['role'], unique=False)
    op.create_index('ix_admins_username', 'admins', ['username'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_categories_ck_categories_no_self_parent')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_categories_ck_categories_sort_order_non_neg')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('parent_id', 'name', name='uq_categories_parent_id_name'),
    sa.UniqueConstraint('parent_id', 'slug', name='uq_categories_parent_id_slug')
    )
    op.create_index('ix_categories_parent_active', 'categories', ['parent_id', 'is_active'], unique=False)
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('ix_categories_sort_order', 'categories', ['sort_order'], unique=False)
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_admin_actions_admin_id_admins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_actions'))
    )
    op.create_index('ix_admin_actions_action_type', 'admin_actions', ['action_type'], unique=False)
    op.create_index('ix_admin_actions_admin_entity', 'admin_actions', ['admin_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_admin_actions_admin_id', 'admin_actions', ['admin_id'], unique=False)
    op.create_index('ix_admin_actions_admin_tg_id', 'admin_actions', ['admin_tg_id'], unique=False)
    op.create_index('ix_admin_actions_entity', 'admin_actions', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_admin_actions_entity_id', 'admin_actions', ['entity_id'], unique=False)
    op.create_index('ix_admin_actions_entity_type', 'admin_actions', ['entity_type'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_text', sa.String(length=100), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'HIDDEN', 'ARCHIVED', name='item_status'), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_rental_period', sa.Integer(), nullable=False),
    sa.Column('max_rental_period', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(max_rental_period IS NULL) OR (max_rental_period >= min_rental_period)', name=op.f('ck_items_ck_items_max_ge_min')),
    sa.CheckConstraint('available_quantity >= 0', name=op.f('ck_items_ck_items_available_quantity_non_neg')),
    sa.CheckConstraint('min_rental_period >= 1', name=op.f('ck_items_ck_items_min_period')),
    sa.CheckConstraint('orders_count >= 0', name=op.f('ck_items_ck_items_orders_non_neg')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_items_ck_items_price_non_neg')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_items_ck_items_sort_order_non_neg')),
    sa.CheckConstraint('views_count >= 0', name=op.f('ck_items_ck_items_views_non_neg')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_items_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], name=op.f('fk_items_created_by_admin_id_admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['categories.id'], name=op.f('fk_items_subcategory_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admins.id'], name=op.f('fk_items_updated_by_admin_id_admins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index('ix_items_category_id', 'items', ['category_id'], unique=False)
    op.create_index('ix_items_category_status', 'items', ['category_id', 'status'], unique=False)
    op.create_index('ix_items_featured', 'items', ['is_featured'], unique=False)
    op.create_index('ix_items_sort_order', 'items', ['sort_order'], unique=False)
    op.create_index('ix_items_status', 'items', ['status'], unique=False)
    op.create_index('ix_items_subcategory_id', 'items', ['subcategory_id'], unique=False)
    op.create_index('ix_items_subcategory_status', 'items', ['subcategory_id', 'status'], unique=False)
    op.create_index('ix_items_subcategory_status_sort', 'items', ['subcategory_id', 'status', 'sort_order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'BANNED', name='account_status'), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banned_by_admin_id'], ['admins.id'], name=op.f('fk_users_banned_by_admin_id_admins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_index('ix_users_account_status', 'users', ['account_status'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('item_characteristics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_item_characteristics_ck_item_characteristics_sort_order_non_neg')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_characteristics_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_characteristics')),
    sa.UniqueConstraint('item_id', 'name', name='uq_item_characteristics_item_id_name')
    )
    op.create_index('ix_item_characteristics_item_id', 'item_characteristics', ['item_id'], unique=False)
    op.create_index('ix_item_characteristics_item_sort_order', 'item_characteristics', ['item_id', 'sort_order'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=500), nullable=True, comment='Telegram file_id, который позволяет отправлять фото без повторной загрузки'),
    sa.Column('url', sa.String(length=1000), nullable=True, comment='URL фотографии, если изображение взято с сайта или внешнего источника'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(telegram_file_id IS NOT NULL) OR (url IS NOT NULL)', name=op.f('ck_photos_ck_photos_has_source')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_photos_ck_photos_order_non_neg')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_photos_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index('ix_photos_item_main', 'photos', ['item_id', 'is_main'], unique=False)
    op.create_index('uq_photos_one_main_per_item', 'photos', ['item_id'], unique=True, postgresql_where=sa.text('is_main IS TRUE'))
    op.create_index('ix_photos_item_order', 'photos', ['item_id', 'sort_order'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rental_period_text', sa.String(length=100), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('requested', 'in_progress', 'confirmed', 'rejected', 'completed', 'cancelled_by_client', 'cancelled_by_admin', name='rental_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_needed', sa.Boolean(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=True),
    sa.Column('client_phone', sa.String(length=30), nullable=True),
    sa.Column('client_comment', sa.Text(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('in_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(final_price IS NULL) OR (final_price >= 0)', name=op.f('ck_rentals_ck_rentals_final_price_non_neg')),
    sa.CheckConstraint('(start_date IS NULL AND end_date IS NULL) OR (start_date IS NOT NULL AND end_date IS NOT NULL AND end_date > start_date)', name=op.f('ck_rentals_ck_rentals_end_after_start')),
    sa.CheckConstraint('(total_price IS NULL) OR (total_price >= 0)', name=op.f('ck_rentals_ck_rentals_total_price_non_neg')),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_rentals_ck_rentals_quantity_positive')),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admins.id'], name=op.f('fk_rentals_assigned_admin_id_admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_rentals_item_id_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rentals_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rentals'))
    )
    op.create_index('ix_rentals_assigned_admin_status', 'rentals', ['assigned_admin_id', 'status'], unique=False)
    op.create_index('ix_rentals_item_id', 'rentals', ['item_id'], unique=False)
    op.create_index('ix_rentals_item_status', 'rentals', ['item_id', 'status'], unique=False)
    op.create_index('ix_rentals_status', 'rentals', ['status'], unique=False)
    op.create_index('ix_rentals_user_id', 'rentals', ['user_id'], unique=False)
    op.create_index('ix_rentals_user_status', 'rentals', ['user_id', 'status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'published', 'hidden', 'rejected', name='review_status'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_reviews_item_id_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name=op.f('fk_reviews_rental_id_rentals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('rental_id', 'user_id', name='uq_reviews_rental_user')
    )
    op.create_index('ix_reviews_item_id', 'reviews', ['item_id'], unique=False)
    op.create_index('ix_reviews_item_rating', 'reviews', ['item_id', 'rating'], unique=False)
    op.create_index('ix_reviews_item_status', 'reviews', ['item_id', 'status'], unique=False)
    op.create_index('ix_reviews_rental_id', 'reviews', ['rental_id'], unique=False)
    op.create_index('ix_reviews_rental_user', 'reviews', ['rental_id', 'user_id'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('rental_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='support_ticket_status'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(closed_at IS NULL AND closed_by_admin_id IS NULL) OR (closed_at IS NOT NULL AND closed_by_admin_id IS NOT NULL)', name=op.f('ck_support_tickets_ck_support_tickets_closed_fields_consistent')),
    sa.ForeignKeyConstraint(['closed_by_admin_id'], ['admins.id'], name=op.f('fk_support_tickets_closed_by_admin_id_admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_support_tickets_item_id_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name=op.f('fk_support_tickets_rental_id_rentals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_tickets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets'))
    )
    op.create_index('ix_support_tickets_closed_by_admin_id', 'support_tickets', ['closed_by_admin_id'], unique=False)
    op.create_index('ix_support_tickets_item_id', 'support_tickets', ['item_id'], unique=False)
    op.create_index('ix_support_tickets_rental_id', 'support_tickets', ['rental_id'], unique=False)
    op.create_index('ix_support_tickets_request_status', 'support_tickets', ['rental_id', 'status'], unique=False)
    op.create_index('ix_support_tickets_status', 'support_tickets', ['status'], unique=False)
    op.create_index('ix_support_tickets_status_created', 'support_tickets', ['status', 'created_at'], unique=False)
    op.create_index('ix_support_tickets_user_id', 'support_tickets', ['user_id'], unique=False)
    op.create_index('ix_support_tickets_user_status', 'support_tickets', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_tickets_user_status', table_name='support_tickets')
    op.drop_index('ix_support_tickets_user_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_status_created', table_name='support_tickets')
    op.drop_index('ix_support_tickets_status', table_name='support_tickets')
    op.drop_index('ix_support_tickets_request_status', table_name='support_tickets')
    op.drop_index('ix_support_tickets_rental_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_item_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_closed_by_admin_id', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_rental_user', table_name='reviews')
    op.drop_index('ix_reviews_rental_id', table_name='reviews')
    op.drop_index('ix_reviews_item_status', table_name='reviews')
    op.drop_index('ix_reviews_item_rating', table_name='reviews')
    op.drop_index('ix_reviews_item_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_rentals_user_status', table_name='rentals')
    op.drop_index('ix_rentals_user_id', table_name='rentals')
    op.drop_index('ix_rentals_status', table_name='rentals')
    op.drop_index('ix_rentals_item_status', table_name='rentals')
    op.drop_index('ix_rentals_item_id', table_name='rentals')
    op.drop_index('ix_rentals_assigned_admin_status', table_name='rentals')
    op.drop_table('rentals')
    op.drop_index('ix_photos_item_order', table_name='photos')
    op.drop_index('uq_photos_one_main_per_item', table_name='photos', postgresql_where=sa.text('is_main IS TRUE'))
    op.drop_index('ix_photos_item_main', table_name='photos')
    op.drop_table('photos')
    op.drop_index('ix_item_characteristics_item_sort_order', table_name='item_characteristics')
    op.drop_index('ix_item_characteristics_item_id', table_name='item_characteristics')
    op.drop_table('item_characteristics')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_account_status', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_items_subcategory_status_sort', table_name='items')
    op.drop_index('ix_items_subcategory_status', table_name='items')
    op.drop_index('ix_items_subcategory_id', table_name='items')
    op.drop_index('ix_items_status', table_name='items')
    op.drop_index('ix_items_sort_order', table_name='items')
    op.drop_index('ix_items_featured', table_name='items')
    op.drop_index('ix_items_category_status', table_name='items')
    op.drop_index('ix_items_category_id', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_admin_actions_entity_type', table_name='admin_actions')
    op.drop_index('ix_admin_actions_entity_id', table_name='admin_actions')
    op.drop_index('ix_admin_actions_entity', table_name='admin_actions')
    op.drop_index('ix_admin_actions_admin_tg_id', table_name='admin_actions')
    op.drop_index('ix_admin_actions_admin_id', table_name='admin_actions')
    op.drop_index('ix_admin_actions_admin_entity', table_name='admin_actions')
    op.drop_index('ix_admin_actions_action_type', table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index('ix_categories_sort_order', table_name='categories')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_index('ix_categories_parent_active', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_admins_username', table_name='admins')
    op.drop_index('ix_admins_role', table_name='admins')
    op.drop_index('ix_admins_is_active', table_name='admins')
    op.drop_index('ix_admins_account_status', table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
