"""initial schema

Revision ID: c0dab82dbe62
Revises: 
Create Date: 2026-02-26 17:45:41.405649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dab82dbe62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_actions'))
    )
    op.create_index('ix_admin_actions_action_type', 'admin_actions', ['action_type'], unique=False)
    op.create_index('ix_admin_actions_admin_id', 'admin_actions', ['admin_id'], unique=False)
    op.create_index('ix_admin_actions_entity', 'admin_actions', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_admin_actions_entity_id', 'admin_actions', ['entity_id'], unique=False)
    op.create_index('ix_admin_actions_entity_type', 'admin_actions', ['entity_type'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_categories_no_self_parent')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('parent_id', 'name', name=op.f('uq_categories_parent_id_name'))
    )
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'BLOCKED', 'BANNED', name='account_status'), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name=op.f('ck_users_ck_users_rating_range')),
    sa.CheckConstraint('rating_count >= 0', name=op.f('ck_users_ck_users_rating_count_nonneg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_index('ix_users_account_status', 'users', ['account_status'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'REJECTED', 'HIDDEN', name='item_status'), nullable=False),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderated_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('min_rental_period', sa.Integer(), nullable=False),
    sa.Column('max_rental_period', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(deposit IS NULL) OR (deposit >= 0)', name=op.f('ck_items_ck_item_deposit_nonneg')),
    sa.CheckConstraint('(max_rental_period IS NULL) OR (max_rental_period >= min_rental_period)', name=op.f('ck_items_ck_item_max_ge_min')),
    sa.CheckConstraint('min_rental_period >= 1', name=op.f('ck_items_ck_item_min_period')),
    sa.CheckConstraint('orders_count >= 0', name=op.f('ck_items_ck_item_orders_nonneg')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_items_ck_item_price_nonneg')),
    sa.CheckConstraint('views_count >= 0', name=op.f('ck_items_ck_item_views_nonneg')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_items_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['moderated_by_admin_id'], ['users.id'], name=op.f('fk_items_moderated_by_admin_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['categories.id'], name=op.f('fk_items_subcategory_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index('ix_items_category_available', 'items', ['category_id', 'is_available'], unique=False)
    op.create_index('ix_items_owner_available', 'items', ['user_id', 'is_available'], unique=False)
    op.create_index('ix_items_status', 'items', ['status'], unique=False)
    op.create_index('ix_items_subcategory_id', 'items', ['subcategory_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='support_ticket_status'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_admin_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_tickets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets'))
    )
    op.create_index('ix_support_tickets_status', 'support_tickets', ['status'], unique=False)
    op.create_index('ix_support_tickets_status_created', 'support_tickets', ['status', 'created_at'], unique=False)
    op.create_index('ix_support_tickets_telegram_id', 'support_tickets', ['telegram_id'], unique=False)
    op.create_index('ix_support_tickets_user_id', 'support_tickets', ['user_id'], unique=False)
    op.create_index('ix_support_tickets_user_status', 'support_tickets', ['user_id', 'status'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=500), nullable=False, comment='Telegram file_id, который позволяет отправлять фото без повторной загрузки'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='позволяет сортировать фото (например, какое показывать первым)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('"sort_order" >= 0', name=op.f('ck_photos_ck_photos_order_nonneg')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_photos_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index('ix_photos_item_order', 'photos', ['item_id', 'sort_order'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'ACTIVE', 'COMPLETED', 'REJECTED_BY_OWNER', 'REJECTED_BY_RENTER', 'CANCELLED_CONFIRMED_BY_OWNER', 'CANCELLED_CONFIRMED_BY_RENTER', 'CANCELLED_BY_OWNER', 'CANCELLED_BY_RENTER', 'DISPUTED', name='rental_status'), nullable=False),
    sa.Column('owner_handover_confirmed', sa.Boolean(), nullable=False),
    sa.Column('renter_receive_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(deposit_amount IS NULL) OR (deposit_amount >= 0)', name=op.f('ck_rentals_ck_rentals_deposit_nonneg')),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_rentals_ck_rentals_end_after_start')),
    sa.CheckConstraint('total_price >= 0', name=op.f('ck_rentals_ck_rentals_total_price_nonneg')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_rentals_item_id_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_rentals_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], name=op.f('fk_rentals_renter_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rentals'))
    )
    op.create_index('ix_rentals_item_id', 'rentals', ['item_id'], unique=False)
    op.create_index('ix_rentals_item_status', 'rentals', ['item_id', 'status'], unique=False)
    op.create_index('ix_rentals_owner_id', 'rentals', ['owner_id'], unique=False)
    op.create_index('ix_rentals_owner_status', 'rentals', ['owner_id', 'status'], unique=False)
    op.create_index('ix_rentals_renter_id', 'rentals', ['renter_id'], unique=False)
    op.create_index('ix_rentals_renter_status', 'rentals', ['renter_id', 'status'], unique=False)
    op.create_index('ix_rentals_status', 'rentals', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewee_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name=op.f('fk_reviews_rental_id_rentals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], name=op.f('fk_reviews_reviewee_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('rental_id', 'reviewer_id', name='uq_reviews_rental_reviewer')
    )
    op.create_index('ix_reviews_rental_id', 'reviews', ['rental_id'], unique=False)
    op.create_index('ix_reviews_reviewee_id', 'reviews', ['reviewee_id'], unique=False)
    op.create_index('ix_reviews_reviewer_id', 'reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_reviewer_id', table_name='reviews')
    op.drop_index('ix_reviews_reviewee_id', table_name='reviews')
    op.drop_index('ix_reviews_rental_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_rentals_status', table_name='rentals')
    op.drop_index('ix_rentals_renter_status', table_name='rentals')
    op.drop_index('ix_rentals_renter_id', table_name='rentals')
    op.drop_index('ix_rentals_owner_status', table_name='rentals')
    op.drop_index('ix_rentals_owner_id', table_name='rentals')
    op.drop_index('ix_rentals_item_status', table_name='rentals')
    op.drop_index('ix_rentals_item_id', table_name='rentals')
    op.drop_table('rentals')
    op.drop_index('ix_photos_item_order', table_name='photos')
    op.drop_table('photos')
    op.drop_index('ix_support_tickets_user_status', table_name='support_tickets')
    op.drop_index('ix_support_tickets_user_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_telegram_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_status_created', table_name='support_tickets')
    op.drop_index('ix_support_tickets_status', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_items_subcategory_id', table_name='items')
    op.drop_index('ix_items_status', table_name='items')
    op.drop_index('ix_items_owner_available', table_name='items')
    op.drop_index('ix_items_category_available', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_account_status', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_admin_actions_entity_type', table_name='admin_actions')
    op.drop_index('ix_admin_actions_entity_id', table_name='admin_actions')
    op.drop_index('ix_admin_actions_entity', table_name='admin_actions')
    op.drop_index('ix_admin_actions_admin_id', table_name='admin_actions')
    op.drop_index('ix_admin_actions_action_type', table_name='admin_actions')
    op.drop_table('admin_actions')
    # ### end Alembic commands ###
